# Generated by Django 5.2.5 on 2025-09-06 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_title_platformreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformreview',
            name='review_text',
            field=models.CharField(max_length=50),
        ),
    ]
