# Generated by Django 5.2.5 on 2025-09-06 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_platformreview_review_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('LEARNER', 'Learner'), ('INSTRUCTOR', 'Instructor'), ('ADMIN', 'Admin')], default='LEARNER', max_length=250),
        ),
    ]
