# Generated by Django 5.2.5 on 2025-09-06 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_profile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformreview',
            name='review_text',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('LEARNER', 'Learner'), ('INSTRUCTOR', 'Instructor'), ('ADMIN', 'Admin')], default='LEARNER', max_length=50),
        ),
    ]
