# Generated by Django 5.2.5 on 2025-09-07 06:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_platformreview_review_text'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='platformreview',
            unique_together={('student', 'rating')},
        ),
    ]
