# Generated by Django 5.2.5 on 2025-09-07 06:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_platformreview_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='platformreview',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='platformreview',
            name='rating',
            field=models.PositiveIntegerField(max_length=5),
        ),
        migrations.AlterField(
            model_name='platformreview',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
