# Generated by Django 5.2.5 on 2025-09-07 06:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_platformreview_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformreview',
            name='rating',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
