# Generated by Django 5.2.5 on 2025-09-04 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_remove_lecture_video_url_course_offer_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='is_draft',
            field=models.BooleanField(default=False),
        ),
    ]
