# Generated by Django 5.2.5 on 2025-09-04 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_is_deleted_course_is_draft'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
