# Generated by Django 5.2.5 on 2025-09-04 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_remove_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='caategory_img',
            field=models.ImageField(blank=True, default='profile_pics/user.png', null=True, upload_to='categoryimage/'),
        ),
    ]
