# Generated by Django 5.2.5 on 2025-09-04 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_category_caategory_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='caategory_img',
            field=models.FileField(blank=True, default='profile_pics/user.png', null=True, upload_to='categoryimage/'),
        ),
    ]
