# Generated by Django 5.2.5 on 2025-09-05 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_alter_review_rating_enrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='hour',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
